<a href="https://colab.research.google.com/github/Kaderye/NumPy-Tutorial/blob/main/NumPy_(Random).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy (Random)**

Random means something that can not be predicted logically.

Random numbers generated through a generation algorithm are called pseudo random.

For truly random number on our computers we need to get the random data from some outside source.

**Generate random integer number**

In [17]:
# generate a random integer number from 0 to 100
from numpy import random
number=random.randint(100)
print(f'The random number is {number}')

The random number is 76


**Generate random float number**

In [18]:
# generate a random float number from 0 to 1
from numpy import random
number=random.rand()
print(f'The random number is {number}')

The random number is 0.03432429458684061


**Generate random array**

In [21]:
# generate a 1-D array containing 5 random integers from 0 to 100
from numpy import random
number=random.randint(100, size=(5))
print(f'The random array: {number}')

The random array: [97 16 35 73 85]


In [25]:
# generate a 1-D array containing 5 random floatings from 0 to 1
from numpy import random
number=random.rand(5)
print(f'The random array: {number}')

The random array: [0.26713958 0.15526405 0.64906536 0.59693212 0.25127439]


In [26]:
# generate a 2-D array with 3 rows, each row containing 4 random integers from 0 to 100
from numpy import random
number=random.randint(100, size=(3, 4))
print(number)

[[67 34 93 96]
 [67 48 14  0]
 [70 44 38 50]]


In [27]:
# generate a 2-D array with 3 rows, each row containing 4 random floatings from 0 to 1
from numpy import random
number=random.rand(3, 4)
print(number)

[[0.41526321 0.29006209 0.16951188 0.85397079]
 [0.35049631 0.38551114 0.8872247  0.01383816]
 [0.25678064 0.46110359 0.49623376 0.83998078]]


**Generate random number from array**

In [34]:
# return one of the values in an array
from numpy import random
number=random.choice([1, 2, 3, 4, 5])
print(number)

2


In [38]:
# generate a 2-D array
from numpy import random
number=random.choice([1, 2, 3, 4, 5], size=(2, 3))
print(number)

[[1 3 5]
 [3 1 4]]
