<a href="https://colab.research.google.com/github/Kaderye/NumPy-Tutorial/blob/main/NumPy_(ufuncs).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy (ufuncs)**

**ufuncs** stands for Universal Functions.

It is operate on the **ndarray** object.

ufuncs are used to implement **vectorization** (converting iterative statements into a vector based operation is called vectorization) in NumPy.



Three arguments are:

**where** : boolean array where the operations should take place.

**dtype** : difining the return type of items.

**out** : output array where the return value should be copied.

In [ ]:
# add two lists using zip() method [without ufuncs]
list_1=[1, 2, 3, 4, 5]
list_2=[6, 7, 8, 9, 10]

list=[]
for i, j in zip(list_1, list_2):
  list.append(i+j)
print(list)

[7, 9, 11, 13, 15]


In [56]:
# add two lists using add() method [with ufuncs]
import numpy as np

list_1=[1, 2, 3, 4, 5]
list_2=[6, 7, 8, 9, 10]

list=np.add(list_1, list_2)
print(list)

[ 7  9 11 13 15]


In [ ]:
# subtract two list usign subtract() method [with ufuncs]
import numpy as np

list_1=[1, 2, 3, 4, 5]
list_2=[6, 7, 8, 9, 10]

list=np.subtract(list_1, list_2)
print(list)

[-5 -5 -5 -5 -5]


In [ ]:
# multiply two list usign multiply() method [with ufuncs]
import numpy as np

list_1=[1, 2, 3, 4, 5]
list_2=[6, 7, 8, 9, 10]

list=np.multiply(list_1, list_2)
print(list)

[ 6 14 24 36 50]


**Create your own ufunc**

To create a function we used **frompyfunc()** method.

The arguments of frompyfunc():

**function** : the name of the function

**inputs** : the number of input arrays

**outputs**: the number of output arrays

In [16]:
# create a sample of ufunc for addition
import numpy as np

def add(number_1, number_2):
  return number_1+number_2

result=np.frompyfunc(add, 2, 1)

print(result([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))

[7 9 11 13 15]


In [17]:
# create a sample of ufunc for addition
import numpy as np

def add(number_1, number_2, number_3):
  return number_1+number_2+number_3

result=np.frompyfunc(add, 3, 1)

print(result([1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [5, 4, 3, 2, 1]))

[12 13 14 15 16]


**Check if a function is a ufunc**

In [18]:
# check if a function is a ufunc
import numpy as np

print(type(np.add))

<class 'numpy.ufunc'>


In [19]:
# check another
import numpy as np

print(type(np.concatenate))

<class 'numpy._ArrayFunctionDispatcher'>


In [21]:
# check another
import numpy as np

print(type(np.gk))

AttributeError: module 'numpy' has no attribute 'gk'

In [22]:
# check anothe way
import numpy as np

if type(np.add)==np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


In [26]:
# check again
import numpy as np

if type(np.subtract)==np.ufunc:
  print('gk is ufunc')
else:
  print('gk is not ufunc')

gk is ufunc


**Simple arithmetic**

Arithmetic operators are + , - , * , / , % , ^ , | | , Q & M

In [27]:
# addition
import numpy as np

array_1=np.array([5, 10, 15, 20, 25])
array_2=np.array([2, 4, 6, 8, 10])

new_array=np.add(array_1, array_2)

print(new_array)

[ 7 14 21 28 35]


In [28]:
# subtraction
import numpy as np

array_1=np.array([5, 10, 15, 20, 25])
array_2=np.array([2, 4, 6, 8, 10])

new_array=np.subtract(array_1, array_2)

print(new_array)

[ 3  6  9 12 15]


In [29]:
# multiplication
import numpy as np

array_1=np.array([5, 10, 15, 20, 25])
array_2=np.array([2, 4, 6, 8, 10])

new_array=np.multiply(array_1, array_2)

print(new_array)

[ 10  40  90 160 250]


In [31]:
# division
import numpy as np

array_1=np.array([5, 10, 15, 20, 25])
array_2=np.array([2, 4, 6, 8, 10])

new_array=np.divide(array_1, array_2)

print(new_array)

[2.5 2.5 2.5 2.5 2.5]


In [34]:
# modulus
import numpy as np

array_1=np.array([5, 10, 15, 20, 25])
array_2=np.array([2, 4, 6, 8, 10])

new_array=np.mod(array_1, array_2)

print(new_array)

[1 2 3 4 5]


In [35]:
# remainder
import numpy as np

array_1=np.array([5, 10, 15, 20, 25])
array_2=np.array([2, 4, 6, 8, 10])

new_array=np.remainder(array_1, array_2)

print(new_array)

[1 2 3 4 5]


In [33]:
# power
import numpy as np

array_1=np.array([5, 10, 15, 20, 25])
array_2=np.array([2, 4, 6, 8, 10])

new_array=np.power(array_1, array_2)

print(new_array)

[            25          10000       11390625    25600000000
 95367431640625]


In [36]:
# quotient and modulus
import numpy as np

array_1=np.array([5, 10, 15, 20, 25])
array_2=np.array([2, 4, 6, 8, 10])

new_array=np.divmod(array_1, array_2)

print(new_array)

(array([2, 2, 2, 2, 2]), array([1, 2, 3, 4, 5]))


In [37]:
# absolute values
import numpy as np

array_1=np.array([-5, 10, -15, -20, -25])

new_array=np.abs(array_1)

print(new_array)

[ 5 10 15 20 25]


**Rounding Decimals**

There are five rounding decimals in NumPy: truncation, fix, rounding, floor, ceil

In [38]:
# truncation
import numpy as np

arr = np.trunc([3.1416245, -7.456785, 0.456812])

print(arr)

[ 3. -7.  0.]


In [39]:
# fix
import numpy as np

arr = np.fix([3.1416245, -7.456785, 0.456812])

print(arr)

[ 3. -7.  0.]


In [40]:
# rounding
import numpy as np

arr = np.round([3.1416245, -7.456785, 0.456812], 3)

print(arr)

[ 3.142 -7.457  0.457]


In [44]:
# floor
import numpy as np

arr = np.floor([3.1416245, -7.456785, 0.456812])

print(arr)

[ 3. -8.  0.]


In [45]:
# ceil
import numpy as np

arr = np.ceil([3.1416245, -7.456785, 0.456812])

print(arr)

[ 4. -7.  1.]


**NumPy Logs**

---



The base is 2, e and 10

In [49]:
# log at base 2
import numpy as np

number=2
print(np.log2(number))

1.0


In [50]:
# log at base 2
import numpy as np

number=np.arange(1, 5)

print(np.log2(number))

[0.        1.        1.5849625 2.       ]


In [51]:
# log at base 10
import numpy as np

number=2
print(np.log10(number))

0.3010299956639812


In [52]:
# log at base 10
import numpy as np

number=np.arange(1, 5)

print(np.log10(number))

[0.         0.30103    0.47712125 0.60205999]


In [53]:
# natural log or log at base e
import numpy as np

number=2
print(np.log(number))

0.6931471805599453


In [54]:
# natural log or log at base e
import numpy as np

number=np.arange(1, 5)

print(np.log(number))

[0.         0.69314718 1.09861229 1.38629436]


In [55]:
# log at any base
from math import log
import numpy as np

nplog=np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


**NumPy Summations**

---



In [57]:
# add two lists using add() method [with ufuncs]
import numpy as np

list_1=[1, 2, 3, 4, 5]
list_2=[6, 7, 8, 9, 10]

list=np.add(list_1, list_2)
print(list)

[ 7  9 11 13 15]


In [60]:
# sum the values in list_1 and list_2
import numpy as np

list_1=[1, 2, 3, 4, 5]
list_2=[6, 7, 8, 9, 10]

list=np.sum([list_1, list_2])
print(list)

55


In [61]:
# sum the values in list_1 and list_2 with axis=1
import numpy as np

list_1=[1, 2, 3, 4, 5]
list_2=[6, 7, 8, 9, 10]

list=np.sum([list_1, list_2], axis=1)
print(list)

[15 40]


In [65]:
# cummulative sum
import numpy as np

list_1=[1, 2, 3, 4, 5]

list=np.cumsum(list_1)
print(list)

[ 1  3  6 10 15]


In [63]:
# cummulative sum
import numpy as np

list_1=[1, 2, 3, 4, 5]
list_2=[6, 7, 8, 9, 10]

list=np.cumsum([list_1, list_2], axis=1)
print(list)

[[ 1  3  6 10 15]
 [ 6 13 21 30 40]]


**NumPy Products**

---



In [69]:
# find the product using prod() method
import numpy as np

list_1=[1, 2, 3, 4, 5]

list=np.prod(list_1)
print(list)

120


In [70]:
# find the product of two lists using prod() method
import numpy as np

list_1=[1, 2, 3, 4, 5]
list_2=[6, 7, 8, 9, 10]

list=np.prod([list_1, list_2])
print(list)

3628800


In [71]:
# find the product of two lists using prod() method with axis=1
import numpy as np

list_1=[1, 2, 3, 4, 5]
list_2=[6, 7, 8, 9, 10]

list=np.prod([list_1, list_2], axis=1)
print(list)

[  120 30240]


In [74]:
# find the cummulative product using prod() method
import numpy as np

list_1=[1, 2, 3, 4, 5]

list=np.cumprod(list_1)
print(list)

[  1   2   6  24 120]


In [72]:
# find the cummulative product of two lists using prod() method
import numpy as np

list_1=[1, 2, 3, 4, 5]
list_2=[6, 7, 8, 9, 10]

list=np.cumprod([list_1, list_2])
print(list)

[      1       2       6      24     120     720    5040   40320  362880
 3628800]


**NumPy Differences**

---



In [75]:
# find the differences
import numpy as np

arr=np.array([5, 10, 5, 20, 35, 15])
new_arr=np.diff(arr)
print(new_arr)

[  5  -5  15  15 -20]


In [87]:
# find the differences
import numpy as np

arr=np.array([5, 10, 5, 20, 35, 15])
new_arr=np.diff(arr, n=2)
print(new_arr)

[-10  20   0 -35]


In [88]:
# find the differences
import numpy as np

arr=np.array([5, 10, 5, 20, 35, 15])
new_arr=np.diff(arr, n=3)
print(new_arr)

[ 30 -20 -35]


In [89]:
# find the differences
import numpy as np

arr=np.array([5, 10, 5, 20, 35, 15])
new_arr=np.diff(arr, n=4)
print(new_arr)

[-50 -15]


In [92]:
# find the differences
import numpy as np

arr=np.array([5, 10, 5, 20, 35, 15])
new_arr=np.diff(arr, n=5)
print(new_arr)

[35]


**NumPy LCM (Lowest Common Multiple) or LCF (Lowest Common Factor)**

---



The **reduce()** method will use the ufunc, in this case the **lcm()** function, on each element, and reduce the array by one dimension.

In [93]:
# find the LCM
import numpy as np

number_1=30
number_2=5

result=np.lcm(number_1, number_2)

print(result)

30


In [99]:
# find the LCM of an array
import numpy as np

arr=np.array([6, 12, 18])
result=np.lcm.reduce(arr)
print(result)

36


In [101]:
# find the LCM of a range
import numpy as np

arr=np.arange(1, 10)
result=np.lcm.reduce(arr)
print(result)

2520


**NumPy GCD (Greatest Common Devisor) or HCF (Highest Common Factor)**

---



The **reduce()** method will use the ufunc, in this case the **gcd()** function, on each element, and reduce the array by one dimension.

In [98]:
# find the GCD
import numpy as np

number_1=30
number_2=5

result=np.gcd(number_1, number_2)

print(result)

5


In [100]:
# find the GCD of an array
import numpy as np

arr=np.array([6, 12, 18])
result=np.gcd.reduce(arr)
print(result)

6


In [102]:
# find the GCD of a range
import numpy as np

arr=np.arange(1, 10)
result=np.gcd.reduce(arr)
print(result)

1


**NumPy Trigonometric Functions**

---



NumPy provides the ufuncs **sin(), cos() and tan()** that take values in radians and produce the corresponding sin, cos and tan values.

In [111]:
# find sin value of pi/2
import numpy as np

number=np.sin(np.pi/2)
print(number)

1.0


In [112]:
# find cos value of pi/2
import numpy as np

number=np.cos(np.pi/2)
print(number)

6.123233995736766e-17


In [113]:
# find tan value of pi/2
import numpy as np

number=np.tan(np.pi/2)
print(number)

1.633123935319537e+16


In [104]:
# find sin values of an array
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [114]:
# find cos values of an array
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.cos(arr)
print(x)

[6.12323400e-17 5.00000000e-01 7.07106781e-01 8.09016994e-01]


In [115]:
# find tan values of an array
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.tan(arr)
print(x)

[1.63312394e+16 1.73205081e+00 1.00000000e+00 7.26542528e-01]


**Convert degrees into radians**

Radians values are pi/180 * degree_values.

In [118]:
# find the radians
import numpy as np

arr = np.array(90)
result = np.deg2rad(arr)
print(result)

1.5707963267948966


In [117]:
# find the radians of an array
import numpy as np

arr = np.array([90, 180, 270, 360])
result = np.deg2rad(arr)
print(result)

[1.57079633 3.14159265 4.71238898 6.28318531]


**Convert radians into degrees**

In [119]:
# find the degree
import numpy as np

arr = np.array(np.pi/2)
result = np.rad2deg(arr)
print(result)

90.0


In [120]:
# find the degrees of an array
import numpy as np

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
result = np.rad2deg(arr)
print(result)

[ 90. 180. 270. 360.]


**Finding angles**

NumPy provides ufuncs **arcsin(), arccos() and arctan()** that produce radian values for corresponding sin, cos and tan values given.

In [108]:
# find the angle of 1
import numpy as np

value = np.arcsin(1)
print(value)

1.5707963267948966


In [124]:
# find the angle of 1
import numpy as np

value = np.arccos(1)
print(value)

0.0


In [125]:
# find the angle of 1
import numpy as np

value = np.arctan(1)
print(value)

0.7853981633974483


**Angles of each value in arrays**

In [126]:
# find the angle of an array
import numpy as np

arr = np.array([1, -1, 0.1])
result = np.arcsin(arr)
print(result)

[ 1.57079633 -1.57079633  0.10016742]


In [127]:
# find the angle of an array
import numpy as np

arr = np.array([1, -1, 0.1])
result = np.arccos(arr)
print(result)

[0.         3.14159265 1.47062891]


In [128]:
# find the angle of an array
import numpy as np

arr = np.array([1, -1, 0.1])
result = np.arctan(arr)
print(result)

[ 0.78539816 -0.78539816  0.09966865]


**Hypotenues**

NumPy provides the **hypot()** function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.

In [129]:
# Find the hypotenues for 4 base and 3 perpendicular
import numpy as np

base = 4
perp = 3

result = np.hypot(base, perp)
print(result)

5.0


In [130]:
# Find the hypotenues for 3 base and 4 perpendicular
import numpy as np

base = 3
perp = 4

result = np.hypot(base, perp)
print(result)

5.0


**NumPy Hyperbolic Functions**

---



NumPy provides the ufuncs **sinh(), cosh() and tanh()** that take values in radians and produce the corresponding sinh, cosh and tanh values.

In [132]:
# find sinh value of pi/2
import numpy as np

result = np.sinh(np.pi/2)
print(result)

2.3012989023072947


In [133]:
# find cosh value of pi/2
import numpy as np

result = np.cosh(np.pi/2)
print(result)

2.5091784786580567


In [134]:
# find tanh value of pi/2
import numpy as np

result = np.tanh(np.pi/2)
print(result)

0.9171523356672744


In [135]:
# find sinh values of an array
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
result = np.sinh(arr)
print(result)

[2.3012989  1.24936705 0.86867096 0.670484  ]


In [136]:
# find cosh values of an array
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
result = np.cosh(arr)
print(result)

[2.50917848 1.60028686 1.32460909 1.20397209]


In [137]:
# find tanh values of an array
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
result = np.tanh(arr)
print(result)

[0.91715234 0.78071444 0.6557942  0.55689331]


**Finding angles**

Numpy provides ufuncs **arcsinh(), arccosh() and arctanh()** that produce radian values for corresponding sinh, cosh and tanh values given.

In [138]:
# find the angle of 1
import numpy as np

value = np.arcsinh(1)
print(value)

0.881373587019543


In [141]:
# find the angle of 1
import numpy as np

value = np.arccosh(1)
print(value)

0.0


In [144]:
# find the angle of 1
import numpy as np

value = np.arctanh(1)
print(value)

inf


<ipython-input-144-27019c9f26d0>:4: RuntimeWarning: divide by zero encountered in arctanh
  value = np.arctanh(1)


**Angles of each value in arrays**

In [145]:
# find the angle of an array
import numpy as np

arr = np.array([0.1, 0.2, 0.5])
result = np.arcsinh(arr)
print(result)

[0.09983408 0.19869011 0.48121183]


In [146]:
# find the angle of an array
import numpy as np

arr = np.array([0.1, 0.2, 0.5])
result = np.arccosh(arr)
print(result)

[nan nan nan]


<ipython-input-146-2bcf93b99ca0>:5: RuntimeWarning: invalid value encountered in arccosh
  result = np.arccosh(arr)


In [147]:
# find the angle of an array
import numpy as np

arr = np.array([0.1, 0.2, 0.5])
result = np.arctanh(arr)
print(result)

[0.10033535 0.20273255 0.54930614]


**NumPy Set Operations**

---



A set in mathematics is a collection of unique elements.

Sets are used for operations involving frequent intersection, union and difference operations.

In [158]:
# create sets in numpy
# We can use NumPy's unique() method to find unique elements from any array.
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
result = np.unique(arr)
print(result)

[1 2 3 4 5 6 7]


In [157]:
# find the union
# To find the unique values of two arrays, use the union1d() method.
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [156]:
# find the intersection
# To find only the values that are present in both arrays, use the intersect1d() method.
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


In [155]:
# find the difference
# To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


In [154]:
# find the symmetric difference
# To find only the values that are NOT present in BOTH sets, use the setxor1d() method.
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
