<a href="https://colab.research.google.com/github/Kaderye/NumPy-Tutorial/blob/main/NumPy_(ufuncs).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy (ufuncs)**

**ufuncs** stands for Universal Functions.

It is operate on the **ndarray** object.

ufuncs are used to implement **vectorization** (converting iterative statements into a vector based operation is called vectorization) in NumPy.



Three arguments are:

**where** : boolean array where the operations should take place.

**dtype** : difining the return type of items.

**out** : output array where the return value should be copied.

In [2]:
# add two lists using zip() method [without ufuncs]
list_1=[1, 2, 3, 4, 5]
list_2=[6, 7, 8, 9, 10]

list=[]
for i, j in zip(list_1, list_2):
  list.append(i+j)
print(list)

[7, 9, 11, 13, 15]


In [4]:
# add two lists using add() method [with ufuncs]
import numpy as np

list_1=[1, 2, 3, 4, 5]
list_2=[6, 7, 8, 9, 10]

list=np.add(list_1, list_2)
print(list)

[ 7  9 11 13 15]


In [6]:
# subtract two list usign subtract() method [with ufuncs]
import numpy as np

list_1=[1, 2, 3, 4, 5]
list_2=[6, 7, 8, 9, 10]

list=np.subtract(list_1, list_2)
print(list)

[-5 -5 -5 -5 -5]


In [8]:
# multiply two list usign multiply() method [with ufuncs]
import numpy as np

list_1=[1, 2, 3, 4, 5]
list_2=[6, 7, 8, 9, 10]

list=np.multiply(list_1, list_2)
print(list)

[ 6 14 24 36 50]


**Create your own ufunc**

To create a function we used **frompyfunc()** method.

The arguments of frompyfunc():

**function** : the name of the function

**inputs** : the number of input arrays

**outputs**: the number of output arrays