<a href="https://colab.research.google.com/github/Kaderye/NumPy-Tutorial/blob/main/NumPy_(Basic).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Tutorial (Basic)**

**NumPy Introduction**

---



NumPy stands for Numerical Python.

It is a python library used for working with arrays.

NumPy was created by Travis Oliphant in 2005.

It is an open source project.

**Why use NumPy?**

NumPy provides an array object that is up to 50x faster than traditional python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions.

**NumPy codebase:** https://github.com/numpy/numpy

**NumPy Getting Started**

---



If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

C:\Users\Your Name>**pip install numpy**

If this command fails, then use a python distribution that already has NumPy istalled like, Anaconda, Spyder.

In [ ]:
# import NumPy module
import numpy
number_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr = numpy.array(number_list)
print(f"The output of array: {arr}")
print(f"The type of NumPy is: {type(arr)}")

The output of array: [ 1  2  3  4  5  6  7  8  9 10]
The type of NumPy is: <class 'numpy.ndarray'>


In [ ]:
# import NumPy module as np
import numpy as np
name_list = ['Abdul', 'Karim', 'Shohan', 'Razon', 'Mizan']
arr = np.array(name_list)
print(f"The output of array: {arr}")
print(f"The type of NumPy is: {type(arr)}")

The output of array: ['Abdul' 'Karim' 'Shohan' 'Razon' 'Mizan']
The type of NumPy is: <class 'numpy.ndarray'>


In [ ]:
# checking the version of NumPy
import numpy as np
print(f"The isntalled version is: {np.__version__}")

The isntalled version is: 2.0.2


**NumPy Getting Arrays**

---



In [ ]:
# NumPy is used to work with arrays. The array object in NumPy is called ndarray.

# create a NumPy ndarray oject
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"The output of array: {arr}")
print(f"The type of NumPy is: {type(arr)}")

# type() is used to see the type of the object.

The output of array: [ 1  2  3  4  5  6  7  8  9 10]
The type of NumPy is: <class 'numpy.ndarray'>


**Create a NumPy ndarray object**

To create an ndarray, we can pass a list, tuple or any array like object into the array() method, and it will be converted into an ndarray.

In [ ]:
# use a tuple to create a numpy array
import numpy as np
mix_tuple=('Shohan', 15, '&&', -33, 'A')
arr=np.array(mix_tuple)
print(f"The output of tuple : {arr}")

The output of tuple : ['Shohan' '15' '&&' '-33' 'A']


**Dimenstions in arrays**

A dimensions in arrays is one level of array depth (nested arrays).

nested arrays are arrays that have arrays as their elements.

**0-D arrays**

In [ ]:
# create a 0-D array or scalars array with the value 150
import numpy as np
arr = np.array(150)
print(f"The output of 0-D array is: {arr}")


The output of 0-D array is: 150


**1-D arrays**

In [ ]:
# create a 1-D array or uni-dimensional array
import numpy as np
name_list=['Sujon', 'Razon', 'Shohan', 'Jodu', 'Modu']
arr=np.array(name_list)
print(f"The output of 1-D array: {arr}")

The output of 1-D array: ['Sujon' 'Razon' 'Shohan' 'Jodu' 'Modu']


**2-D arrays**

In [ ]:
# create a 2-D arrays, it is used to represent matrix or 2nd order tensors.
import numpy as np
matrix_number=[[1, 2, 3], [4, 5, 6]]
arr=np.array(matrix_number)
print(f"The output of 2-D array: \n{arr}")

The output of 2-D array: 
[[1 2 3]
 [4 5 6]]


**3-D arrays**

In [ ]:
# another 3-D arrays with two 2-D arrays
import numpy as np
matrix_number=[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [6, 3, 1]]]
arr=np.array(matrix_number)
print(f"The output of 3-D array: \n{arr}")

The output of 3-D array: 
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [6 3 1]]]


**Check number of dimensions**

In [ ]:
# check number of dimensions
import numpy as np
arr = np.array(150)
print(f"The number of dimensions at 0-D array is: {arr.ndim}")

name_list=['Sujon', 'Razon', 'Shohan', 'Jodu', 'Modu']
arr=np.array(name_list)
print(f"The number of dimensions at 1-D array is: {arr.ndim}")

matrix_number=[[1, 2, 3], [4, 5, 6]]
arr=np.array(matrix_number)
print(f"The number of dimensions at 2-D array is: {arr.ndim}")

matrix_number=[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [6, 3, 1]]]
arr=np.array(matrix_number)
print(f"The number of dimensions at 3-D array is: {arr.ndim}")

The number of dimensions at 0-D array is: 0
The number of dimensions at 1-D array is: 1
The number of dimensions at 2-D array is: 2
The number of dimensions at 3-D array is: 3


**Higher dimensional arrays**

In [ ]:
# when the array is created, you can define the number of dimensions
import numpy as np
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
print(f"The output: \n{arr}")
print(f"The number of dimensions : {arr.ndim}")

The output: 
[[[[[1 2 3 4 5]]]]]
The number of dimensions : 5


In this array the innermost dimension (5th dim) has 4 elements,

the 4th dim has 1 element that is the vector,

the 3rd dim has 1 element that is the matrix with the vector,

the 2nd dim has 1 element that is 3D array

and 1st dim has 1 element that is a 4D array.

**NumPy array indexing**

Array indexing is the same as accessing an array element.

The index start with 0 to N.

**Access 1-D arrays**

In [ ]:
# get the first element of an array
import numpy as np
arr = np.array([12, 14, 16, 18, 20, 22, 24])
print(f"The first element is: {arr[0]}")

The first element is: 12


In [ ]:
# get the second element of an array
import numpy as np
arr = np.array([12, 14, 16, 18, 20, 22, 24])
print(f"The second element is: {arr[1]}")

The second element is: 14


In [ ]:
# get the last element of an array
import numpy as np
arr = np.array([12, 14, 16, 18, 20, 22, 24])
print(f"The last element is: {arr[6]}")

The last element is: 24


In [ ]:
# arithmetic operations between fourth and sixth elements
import numpy as np
arr = np.array([12, 14, 16, 18, 20, 22, 24])
print(f"The summation of {arr[3]} and {arr[5]} is: {arr[3] + arr[5]}")
print(f"The subtraction of {arr[3]} and {arr[5]} is: {arr[3] - arr[5]}")
print(f"The multiplicaiton of {arr[3]} and {arr[5]} is: {arr[3] * arr[5]}")
print(f"The division of {arr[3]} and {arr[5]} is: {arr[3] / arr[5]}")
print(f"The modulus of {arr[3]} and {arr[5]} is: {arr[3] % arr[5]}")

The summation of 18 and 22 is: 40
The subtraction of 18 and 22 is: -4
The multiplicaiton of 18 and 22 is: 396
The division of 18 and 22 is: 0.8181818181818182
The modulus of 18 and 22 is: 18


**Access 2-D arrays**

In [ ]:
# create a 2-D arrays, it is used to represent matrix or 2nd order tensors.
import numpy as np
matrix_number=[[1, 2, 3], [4, 5, 6]]
arr=np.array(matrix_number)
print(f"The 2nd element on 1st row: {arr[0, 1]}")
print(f"The 2nd element on 2nd row: {arr[1, 1]}")
print(f"The 3rd element on 1st row: {arr[0, 2]}")

The 2nd element on 1st row: 2
The 2nd element on 2nd row: 5
The 3rd element on 1st row: 3


**Access 3-D arrays**

In [ ]:
# another 3-D arrays with two 2-D arrays
import numpy as np
matrix_number=[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [6, 3, 1]]]
arr=np.array(matrix_number)
print(f"The 3rd element of the 2nd array of the 1st array: {arr[0, 1, 2]}")
print(f"The 2nd element of the 2nd array of the 2nd array: {arr[1, 1, 1]}")
print(f"The 1st element of the 1st array of the 2nd array: {arr[1, 0, 0]}")

The 3rd element of the 2nd array of the 1st array: 6
The 2nd element of the 2nd array of the 2nd array: 3
The 1st element of the 1st array of the 2nd array: 7


**Negative indexing**

In [ ]:
# create a 2-D arrays, it is used to represent matrix or 2nd order tensors.
import numpy as np
matrix_number=[[1, 2, 3], [4, 5, 6]]
arr=np.array(matrix_number)
print(f"The last element from 2nd dim: {arr[1, -1]}")
print(f"The 2nd element on 2nd row: {arr[1, -2]}")
print(f"The 2nd element on 2nd row: {arr[-1, -2]}")
print(f"The 1st element on 1st row: {arr[0, -3]}")
print(f"The 1st element on 2nd row: {arr[-1, -3]}")

The last element from 2nd dim: 6
The 2nd element on 2nd row: 5
The 2nd element on 2nd row: 5
The 1st element on 1st row: 1
The 1st element on 2nd row: 4


**NumPy Array Slicing**

---



Slicing means taking elements from one given index to another given index.

1st way: [start : end]

2nd way: [start : end : step]

In [ ]:
# print the elements from index 0 to 5
import numpy as np
number_list=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr= np.array(number_list)
print(f"The elements from index 0 to 5: {arr[0:6]}")
print(f"The elements from index 3 to 7: {arr[3:8]}")

The elements from index 0 to 5: [1 2 3 4 5 6]
The elements from index 3 to 7: [4 5 6 7 8]


In [ ]:
print(f"The elements from index 4 to the end: {arr[4:]}")

The elements from index 4 to the end: [ 5  6  7  8  9 10]


In [ ]:
print(f"The elements from index first to 5: {arr[:6]}")

The elements from index first to 5: [1 2 3 4 5 6]


**Negative slicing**

In [ ]:
# print the elements from index 3 to 1
import numpy as np
number_list=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr= np.array(number_list)
print(f"The elements from index 3 to 1: {arr[-9 : -6]}")

print(f"The elements from index 1 to 3: {arr[1 : 4]}")

The elements from index 3 to 1: [2 3 4]
The elements from index 1 to 3: [2 3 4]


**STEP**

**Slicing 1-D arrays**

In [ ]:
import numpy as np
number_list=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr= np.array(number_list)
print(f"The elements from index 0 to 10 with step 2: {arr[0 : 10 : 2]}")
print(f"The elements from index 0 to 10 with step 2: {arr[ : : 2]}")
print(f"The elements from index 1 to 10 with step 2: {arr[1 : 10 : 2]}")
print(f"The elements from index 1 to 10 with step 2: {arr[ 1: : 2]}")

The elements from index 0 to 10 with step 2: [1 3 5 7 9]
The elements from index 0 to 10 with step 2: [1 3 5 7 9]
The elements from index 1 to 10 with step 2: [ 2  4  6  8 10]
The elements from index 1 to 10 with step 2: [ 2  4  6  8 10]


**Slicing 2-D arrays**

In [ ]:
# create a 2-D arrays, it is used to represent matrix or 2nd order tensors.
import numpy as np
matrix_number=[[1, 2, 3], [4, 5, 6]]
arr=np.array(matrix_number)
print(f"The 2nd element, slice elements from idex 1 to index 2: {arr[1, 1:3]}")
print(f"The 1st element, slice elements from idex 0 to index 2: {arr[0, 0:3]}")

The 2nd element, slice elements from idex 1 to index 2: [5 6]
The 1st element, slice elements from idex 0 to index 2: [1 2 3]


In [ ]:
print(f"From both elements, return index 2: {arr[0:2, 2]}")

From both elements, return index 2: [3 6]


In [ ]:
print(f"From both elements, return index 1 to 2: \n{arr[0:2, 1:3]}")

From both elements, return index 1 to 2: 
[[2 3]
 [5 6]]


**NumPy Data Types**

---



By default Python have these data types:

    strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

    integer - used to represent integer numbers. e.g. -1, -2, -3

    float - used to represent real numbers. e.g. 1.2, 42.42

    boolean - used to represent True or False.
    
    complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j



**NumPy** has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )

**Checking the data types of an array**

In [ ]:
# get the type of an array
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"The type of array is {type(arr)}")

The type of array is <class 'numpy.ndarray'>


In [ ]:
# get the type of an array
import numpy as np
arr=np.array(['A', 'B', 'C', 'D', 'E'])
print(f"The type of array is {type(arr)}")

The type of array is <class 'numpy.ndarray'>


**Creating arrays with a defined data type**

In [ ]:
# create an array with data types string
import numpy as np
arr=np.array([1, 2, 3, 4, 5], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [ ]:
# create an array with data types floating
import numpy as np
arr=np.array([1, 2, 3, 4, 5], dtype='f')
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float32


In [ ]:
# create an array with data types unsigned integer
import numpy as np
arr=np.array([1, 2, 3, 4, 5], dtype='U')
print(arr)
print(arr.dtype)

['1' '2' '3' '4' '5']
<U1


In [ ]:
# create an array with data types integer
import numpy as np
arr=np.array([1, 2, 3, 4, 5], dtype='i')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [ ]:
# create an array with data types 4 bytes integer
import numpy as np
arr=np.array([1, 2, 3, 4, 5], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [ ]:
# create an array with data types 8 bytes integer
import numpy as np
arr=np.array([1, 2, 3, 4, 5], dtype='i8')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


**What if a value can not be converted?**

If a type is given in which elements can not be casted then NumPy will raise a ValueError.

In [ ]:
import numpy as np
arr=np.array(['a', '2', '3', '4', '5'], dtype='i')
print(arr)

ValueError: invalid literal for int() with base 10: 'a'

**Converting data type on existing arrays**

In [ ]:
# using astype()
import numpy as np
arr=np.array([1.1, 2.1, 3.1, 4.1, 5.1])
new_arr=arr.astype('i')
print(new_arr)
print(new_arr.dtype)

[1 2 3 4 5]
int32


In [ ]:
# using astype()
import numpy as np
arr=np.array([1.1, 2.1, 3.1, 4.1, 5.1])
new_arr=arr.astype(int)
print(new_arr)
print(new_arr.dtype)

[1 2 3 4 5]
int64


In [ ]:
# using astype()
import numpy as np
arr=np.array([1.1, 2.1, 0.0, 4.1, 5.1])
new_arr=arr.astype(bool)
print(new_arr)
print(new_arr.dtype)

[ True  True False  True  True]
bool


**NumPy Array Copy vs View**

---



**The copy** is a new array. The copy should not be affected by the changes made to the original array.

**The view** is just a view of the original array. The view should be affected by the changes made to the original array.

**COPY**

In [ ]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5])
new=arr.copy()
print(arr)
print(new)

[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5])
new=arr.copy()
arr[0]=52
print(arr)
print(new)

[52  2  3  4  5]
[1 2 3 4 5]


**VIEW**

In [ ]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5])
new=arr.view()
print(arr)
print(new)

[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5])
new=arr.view()
arr[0]=52
print(arr)
print(new)

[52  2  3  4  5]
[52  2  3  4  5]


**Check if array owns its data**

In [ ]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5])
new_copy=arr.copy()
new_view=arr.view()

print(new_copy.base)
print(new_view.base)

None
[1 2 3 4 5]


**NumPy Array Shape**

---



The shape of an array is the number of elements in each dimension.

In [ ]:
# get the shape of a 2-D array
import numpy as np
arr=np.array([[1, 2, 3, 4, 5] , [6, 7, 8, 9, 10]])
print(f"The shape of a 2-D array is {arr.shape}")

The shape of a 2-D array is (2, 5)


In [ ]:
# create an array with 5 dimensions
import numpy as np
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
print(f'The array is {arr}')
print(f'The shape of array : {arr.shape}')

The array is [[[[[1 2 3 4 5]]]]]
The shape of array : (1, 1, 1, 1, 5)


**NumPy Array Reshaping**

---



Reshaping means changing the shape of an array.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

**Reshape from 1-D to 2-D**

In [ ]:
# create 4 arrays, each with 3 elements
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# create 3 arrays, each with 4 elements
newarr = arr.reshape(3, 4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Reshape from 1-D to 3-D**

In [ ]:
# create 2 arrays that contains 3 arrays, each with 2 elements
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# create 2 arrays that contains 2 arrays, each with 3 elements
newarr = arr.reshape(2, 2, 3)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**Can we reshpe into any shape**

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
newarr = arr.reshape(3, 3)
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Returns Copy or View?**

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


**Unknown Dimension**

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Flattening the arrays**

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [ ]:
# Convert the array into a 1D array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


**NumPy Array Iterating**

---



Iterating means going through elements one by one.

**Iterating 1-D Array**

In [ ]:
# iterating 1-D array
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
for i in arr:
  print(i, end=' ')

1 2 3 4 5 6 7 8 

**Iterating 2-D Array**

In [ ]:
# iterating 2-D array
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
for i in arr:
  print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [ ]:
# iterating 2-D array with each scalar elements
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
for i in arr:
  for j in i:
    print(j, end=' ')

1 2 3 4 5 6 7 8 9 10 

**Iterating 3-D Array**

In [ ]:
# iterating 3-D array
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [5, 4, 6]]])

for i in arr:
  print(i)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [5 4 6]]


In [ ]:
# iterating 3-D array to the scalars
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [5, 4, 6]]])

for i in arr:
  for j in i:
    print(j)

[1 2 3]
[4 5 6]
[7 8 9]
[5 4 6]


In [ ]:
# iterating 3-D array with each scalar elements
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [5, 4, 6]]])

for i in arr:
  for j in i:
    for k in j:
      print(k, end=' ')

1 2 3 4 5 6 7 8 9 5 4 6 

**Iterating Arrays Using nditer()**

nditer() is used to iterating in advanced iterations.

In [ ]:
# iterating 1-D array
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
for i in np.nditer(arr):
  print(i, end=' ')

1 2 3 4 5 6 7 8 

In [ ]:
# iterating 2-D array
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
for i in np.nditer(arr):
  print(i, end=' ')

1 2 3 4 5 6 7 8 9 10 

In [ ]:
# iterating 3-D array
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [5, 4, 6]]])
for i in np.nditer(arr):
  print(i, end=' ')

1 2 3 4 5 6 7 8 9 5 4 6 

**Iterating Array with Different Data Types**

**op_dtypes** argument and pass it the expected datatype to change the datatype of elements while iterating.

In [ ]:
# iterating through the array as a string
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
for i in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(i)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')


**Iterating with Different Step Size**

In [ ]:
# iterating 2-D array skinpping 1 element
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
for i in np.nditer(arr[:, ::2]):
  print(i, end=' ')

1 3 5 6 8 10 

In [ ]:
# iterating 2-D array
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
for i in np.nditer(arr[:, :2]):
  print(i, end=' ')

1 2 6 7 

**Enumerated Iteration Using ndenumerated()**

In [ ]:
# enumerated 1-D array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
for i in np.ndenumerate(arr):
  print(i)

((0,), np.int64(1))
((1,), np.int64(2))
((2,), np.int64(3))
((3,), np.int64(4))
((4,), np.int64(5))


In [ ]:
# enumerated 1-D array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
for idx, i in np.ndenumerate(arr):
  print(idx, i)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [ ]:
# iterating 2-D array
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
for i in np.ndenumerate(arr):
  print(i)

((0, 0), np.int64(1))
((0, 1), np.int64(2))
((0, 2), np.int64(3))
((0, 3), np.int64(4))
((0, 4), np.int64(5))
((1, 0), np.int64(6))
((1, 1), np.int64(7))
((1, 2), np.int64(8))
((1, 3), np.int64(9))
((1, 4), np.int64(10))


In [ ]:
# iterating 2-D array
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
for idx, i in np.ndenumerate(arr):
  print(idx, i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10


**NumPy Joining Array**

---



Joining means putting contents of two or more arrays in a single array.

To join we can use **concatenate()** function.

In [ ]:
# join 1-D arrays
import numpy as np
arr_1=np.array([1, 2, 3, 4, 5])
arr_2=np.array([6, 7, 8, 9, 10])
arr=np.concatenate((arr_1, arr_2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# join 2-D arrays
import numpy as np
arr_1=np.array([[1, 2, 3], [4, 5, 6]])
arr_2=np.array([[7, 8, 9], [10, 11, 12]])
arr=np.concatenate((arr_1, arr_2))
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# join 2-D arrays with axis=1
import numpy as np
arr_1=np.array([[1, 2, 3], [4, 5, 6]])
arr_2=np.array([[7, 8, 9], [10, 11, 12]])
arr=np.concatenate((arr_1, arr_2), axis=1)
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
# join 3-D arrays
import numpy as np
arr_1=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_2=np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
arr=np.concatenate((arr_1, arr_2))
print(arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [ ]:
# join 3-D arrays with axis=1
import numpy as np
arr_1=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_2=np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
arr=np.concatenate((arr_1, arr_2), axis=1)
print(arr)

[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]


In [ ]:
# join 3-D arrays with axis=2
import numpy as np
arr_1=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_2=np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
arr=np.concatenate((arr_1, arr_2), axis=2)
print(arr)

[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


**Joining arrays using stack() function**

In [ ]:
# join 1-D arrays
import numpy as np
arr_1=np.array([1, 2, 3, 4, 5])
arr_2=np.array([6, 7, 8, 9, 10])
arr=np.stack((arr_1, arr_2))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# join 1-D arrays with axis=1
import numpy as np
arr_1=np.array([1, 2, 3, 4, 5])
arr_2=np.array([6, 7, 8, 9, 10])
arr=np.stack((arr_1, arr_2), axis=1)
print(arr)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


**Stacking along rows**

In [ ]:
# join 1-D arrays with hstack()
import numpy as np
arr_1=np.array([1, 2, 3, 4, 5])
arr_2=np.array([6, 7, 8, 9, 10])
arr=np.hstack((arr_1, arr_2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# join 2-D arrays with hstack()
import numpy as np
arr_1=np.array([[1, 2, 3], [4, 5, 6]])
arr_2=np.array([[7, 8, 9], [10, 11, 12]])
arr=np.hstack((arr_1, arr_2))
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
# join 3-D arrays with hstack()
import numpy as np
arr_1=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_2=np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
arr=np.hstack((arr_1, arr_2))
print(arr)

[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]


**Stacking along columns**

In [ ]:
# join 1-D arrays with vstack()
import numpy as np
arr_1=np.array([1, 2, 3, 4, 5])
arr_2=np.array([6, 7, 8, 9, 10])
arr=np.vstack((arr_1, arr_2))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# join 2-D arrays with vstack()
import numpy as np
arr_1=np.array([[1, 2, 3], [4, 5, 6]])
arr_2=np.array([[7, 8, 9], [10, 11, 12]])
arr=np.vstack((arr_1, arr_2))
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# join 3-D arrays with vstack()
import numpy as np
arr_1=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_2=np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
arr=np.vstack((arr_1, arr_2))
print(arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


**Stacking along height (depth)**

In [ ]:
# join 1-D arrays with dstack()
import numpy as np
arr_1=np.array([1, 2, 3, 4, 5])
arr_2=np.array([6, 7, 8, 9, 10])
arr=np.dstack((arr_1, arr_2))
print(arr)

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


In [ ]:
# join 2-D arrays with dstack()
import numpy as np
arr_1=np.array([[1, 2, 3], [4, 5, 6]])
arr_2=np.array([[7, 8, 9], [10, 11, 12]])
arr=np.dstack((arr_1, arr_2))
print(arr)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [ ]:
# join 3-D arrays with dstack()
import numpy as np
arr_1=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_2=np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
arr=np.dstack((arr_1, arr_2))
print(arr)

[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


**Splitting NumPy Arrays**

---



Splitting is reverse operation of joining. It breaks one array into multiple by using **array_split()** function.

In [ ]:
# split the array in 2 parts
import numpy as np
arr= np.array([1, 2, 3, 4, 5])
new_arr=np.array_split(arr, 2)
print(new_arr)

[array([1, 2, 3]), array([4, 5])]


In [ ]:
# split the array in 4 parts
import numpy as np
arr= np.array([1, 2, 3, 4, 5])
new_arr=np.array_split(arr, 4)
print(new_arr)

[array([1, 2]), array([3]), array([4]), array([5])]


**1-D array**

In [ ]:
# access the splitted arrays
import numpy as np
arr=np.array([1, 2, 3, 4, 5])
new_arr=np.array_split(arr, 2)

print(f"The first array is {new_arr[0]}")
print(f"The second array is {new_arr[1]}")

The first array is [1 2 3]
The second array is [4 5]


**2-D array**

In [ ]:
# split the 2-D array into three 2-D arrays
import numpy as np
arr=np.array([[1, 2, 3], [4, 5, 6]])
new_arr=np.array_split(arr, 3)
print(new_arr)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]


In [ ]:
# split the 2-D array into three 2-D arrays with axis=1
import numpy as np
arr=np.array([[1, 2, 3], [4, 5, 6]])
new_arr=np.array_split(arr, 3, axis=1)
print(new_arr)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [ ]:
# split the 2-D array into three 2-D arrays usign hsplit()
import numpy as np
arr=np.array([[1, 2, 3], [4, 5, 6]])
new_arr=np.hsplit(arr, 3)
print(new_arr)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [ ]:
# split the 2-D array into three 2-D arrays usign vsplit()
import numpy as np
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
new_arr=np.vsplit(arr, 3)
print(new_arr)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [ ]:
# split the 3-D array into three 2-D arrays usign dsplit()
import numpy as np
arr=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
new_arr=np.dsplit(arr, 2)
print(new_arr)

[array([[[1],
        [3]],

       [[5],
        [7]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]


**NumPy Searching Arrays**

---



To search an array, use the **where()** method.

In [ ]:
# find the idexes where the value is 7
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 7])
indexNumber=np.where(arr==7)
print(indexNumber)

(array([6, 9]),)


In [ ]:
# find the indexes where the values are even
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
indexNumber=np.where(arr%2==0)
print(indexNumber)

(array([1, 3, 5, 7, 9]),)


In [ ]:
# find the indexes where the values are odd
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
indexNumber=np.where(arr%2!=0)
print(indexNumber)

(array([0, 2, 4, 6, 8]),)


**searchsorted()**

In [ ]:
# find the idexes where the value is 7
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 7])
indexNumber=np.searchsorted(arr, 7)
print(indexNumber)

6


In [ ]:
# find the indexes where the values are even
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
values= arr[arr%2==0]
indexNumber=np.searchsorted(arr, values)
print(indexNumber)

[1 3 5 7 9]


In [ ]:
# find the indexes where the values are odd
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
values= arr[arr%2!=0]
indexNumber=np.searchsorted(arr, values)
print(indexNumber)

[0 2 4 6 8]


**Search from the right side**

In [ ]:
# find the idexes where the value is 7
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 7])
indexNumber=np.searchsorted(arr, 4, side='left')
print(indexNumber)

3


In [ ]:
# find the idexes where the value is 7
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 7])
indexNumber=np.searchsorted(arr, 4, side='right')
print(indexNumber)

4


**Multiple values**

In [ ]:
# find the idexes where the values 3, 7, 5
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 7])
indexNumber=np.searchsorted(arr, [3, 7, 5])
print(indexNumber)

[2 6 4]


**NumPy Sorting Arrays**

---



Sorting means putting elements in an ordered sequence.

To sort we used **sort()** method.

**Sorting 1-D array**

In [ ]:
# sort the array
import numpy as np
arr=np.array([12, 9, 1, 3, 7, 44, 5, 1, 9])
sort_number=np.sort(arr)
print(sort_number)

[ 1  1  3  5  7  9  9 12 44]


In [ ]:
# sort the array alphabetically
import numpy as np
arr=np.array(['Shohan', 'Mizan', 'Razon', 'Abdul'])
sort_name=np.sort(arr)
print(sort_name)

['Abdul' 'Mizan' 'Razon' 'Shohan']


In [ ]:
# sort a boolean array
import numpy as np
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


**Sorting 2-D array**

In [ ]:
# sort a 2-D array
import numpy as np
arr=np.array([[3, 1, 2, 7], [8, 4, 2, 1]])
sort_number=np.sort(arr)
print(sort_number)

[[1 2 3 7]
 [1 2 4 8]]


**Sorting 3-D array**

In [ ]:
# sort a 3-D array
import numpy as np
arr=np.array([[[4, 2, 1], [3, 2, 3]], [[3, 6, 1], [7, 3, 5]]])
sort_number=np.sort(arr)
print(sort_number)

[[[1 2 4]
  [2 3 3]]

 [[1 3 6]
  [3 5 7]]]


**NumPy Filter Array**

---



Getting some items out of an existing array and creating a new array out of them is called filtering.

In [ ]:
# create an array from the elements on index 0 and 2
import numpy as np
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


**Creating filter directly from array**

In [ ]:
# create a filter array that will return only values higher than 35 with sorted
import numpy as np
arr=np.array([12, 45, 22, 78, 33, 21, 55, 23, 74, 88])

filter_arr=arr > 35

new_arr=arr[filter_arr]
print(np.sort(new_arr))

[45 55 74 78 88]


In [ ]:
# create a filter array that will return only even values with sorted
import numpy as np
arr=np.array([12, 45, 22, 78, 33, 21, 55, 23, 74, 88])

filter_arr=arr%2==0

new_arr=arr[filter_arr]
print(np.sort(new_arr))

[12 22 74 78 88]


In [ ]:
# create a filter array that will return only odd values with sorted
import numpy as np
arr=np.array([12, 45, 22, 78, 33, 21, 55, 23, 74, 88])

filter_arr=arr%2!=0

new_arr=arr[filter_arr]
print(np.sort(new_arr))

[21 23 33 45 55]


**Creating the filter array using condition**

In [ ]:
# create a filter array that will return only values higher than 35 with sorted
import numpy as np
arr=np.array([12, 45, 22, 78, 33, 21, 55, 23, 74, 88])

filter_arr=[]

for i in arr:
  if i>35:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

new_arr=arr[filter_arr]
print(np.sort(new_arr))

[45 55 74 78 88]


In [ ]:
# create a filter array that will return only even values with sorted
import numpy as np
arr=np.array([12, 45, 22, 78, 33, 21, 55, 23, 74, 88])

filter_arr=[]

for i in arr:
  if i%2==0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

new_arr=arr[filter_arr]
print(np.sort(new_arr))

[12 22 74 78 88]


In [ ]:
# create a filter array that will return only odd values with sorted
import numpy as np
arr=np.array([12, 45, 22, 78, 33, 21, 55, 23, 74, 88])

filter_arr=[]

for i in arr:
  if i%2!=0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

new_arr=arr[filter_arr]
print(np.sort(new_arr))

[21 23 33 45 55]
