<a href="https://colab.research.google.com/github/Kaderye/NumPy-Tutorial/blob/main/NumPy_Tutorial_(Basic).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Tutorial (Basic)**

**NumPy Introduction**

---



NumPy stands for Numerical Python.

It is a python library used for working with arrays.

NumPy was created by Travis Oliphant in 2005.

It is an open source project.

**Why use NumPy?**

NumPy provides an array object that is up to 50x faster than traditional python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions.

**NumPy codebase:** https://github.com/numpy/numpy

**NumPy Getting Started**

---



If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

C:\Users\Your Name>**pip install numpy**

If this command fails, then use a python distribution that already has NumPy istalled like, Anaconda, Spyder.

In [11]:
# import NumPy module
import numpy
number_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr = numpy.array(number_list)
print(f"The output of array: {arr}")
print(f"The type of NumPy is: {type(arr)}")

The output of array: [ 1  2  3  4  5  6  7  8  9 10]
The type of NumPy is: <class 'numpy.ndarray'>


In [12]:
# import NumPy module as np
import numpy as np
name_list = ['Abdul', 'Karim', 'Shohan', 'Razon', 'Mizan']
arr = np.array(name_list)
print(f"The output of array: {arr}")
print(f"The type of NumPy is: {type(arr)}")

The output of array: ['Abdul' 'Karim' 'Shohan' 'Razon' 'Mizan']
The type of NumPy is: <class 'numpy.ndarray'>


In [14]:
# checking the version of NumPy
import numpy as np
print(f"The isntalled version is: {np.__version__}")

The isntalled version is: 2.0.2


**NumPy Getting Arrays**

---



In [15]:
# NumPy is used to work with arrays. The array object in NumPy is called ndarray.

# create a NumPy ndarray oject
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"The output of array: {arr}")
print(f"The type of NumPy is: {type(arr)}")

# type() is used to see the type of the object.

The output of array: [ 1  2  3  4  5  6  7  8  9 10]
The type of NumPy is: <class 'numpy.ndarray'>


**Create a NumPy ndarray object**

To create an ndarray, we can pass a list, tuple or any array like object into the array() method, and it will be converted into an ndarray.

In [18]:
# use a tuple to create a numpy array
import numpy as np
mix_tuple=('Shohan', 15, '&&', -33, 'A')
arr=np.array(mix_tuple)
print(f"The output of tuple : {arr}")

The output of tuple : ['Shohan' '15' '&&' '-33' 'A']


**Dimenstions in arrays**

A dimensions in arrays is one level of array depth (nested arrays).

nested arrays are arrays that have arrays as their elements.

**0-D arrays**

In [20]:
# create a 0-D array or scalars array with the value 150
import numpy as np
arr = np.array(150)
print(f"The output of 0-D array is: {arr}")


The output of 0-D array is: 150


**1-D arrays**

In [21]:
# create a 1-D array or uni-dimensional array
import numpy as np
name_list=['Sujon', 'Razon', 'Shohan', 'Jodu', 'Modu']
arr=np.array(name_list)
print(f"The output of 1-D array: {arr}")

The output of 1-D array: ['Sujon' 'Razon' 'Shohan' 'Jodu' 'Modu']


**2-D arrays**

In [51]:
# create a 2-D arrays, it is used to represent matrix or 2nd order tensors.
import numpy as np
matrix_number=[[1, 2, 3], [4, 5, 6]]
arr=np.array(matrix_number)
print(f"The output of 2-D array: \n{arr}")

The output of 2-D array: 
[[1 2 3]
 [4 5 6]]


**3-D arrays**

In [27]:
# another 3-D arrays with two 2-D arrays
import numpy as np
matrix_number=[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [6, 3, 1]]]
arr=np.array(matrix_number)
print(f"The output of 3-D array: \n{arr}")

The output of 3-D array: 
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [6 3 1]]]


**Check number of dimensions**

In [30]:
# check number of dimensions
import numpy as np
arr = np.array(150)
print(f"The number of dimensions at 0-D array is: {arr.ndim}")

name_list=['Sujon', 'Razon', 'Shohan', 'Jodu', 'Modu']
arr=np.array(name_list)
print(f"The number of dimensions at 1-D array is: {arr.ndim}")

matrix_number=[[1, 2, 3], [4, 5, 6]]
arr=np.array(matrix_number)
print(f"The number of dimensions at 2-D array is: {arr.ndim}")

matrix_number=[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [6, 3, 1]]]
arr=np.array(matrix_number)
print(f"The number of dimensions at 3-D array is: {arr.ndim}")

The number of dimensions at 0-D array is: 0
The number of dimensions at 1-D array is: 1
The number of dimensions at 2-D array is: 2
The number of dimensions at 3-D array is: 3


**Higher dimensional arrays**

In [42]:
# when the array is created, you can define the number of dimensions
import numpy as np
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
print(f"The output: \n{arr}")
print(f"The number of dimensions : {arr.ndim}")

The output: 
[[[[[1 2 3 4 5]]]]]
The number of dimensions : 5


In this array the innermost dimension (5th dim) has 4 elements,

the 4th dim has 1 element that is the vector,

the 3rd dim has 1 element that is the matrix with the vector,

the 2nd dim has 1 element that is 3D array

and 1st dim has 1 element that is a 4D array.

**NumPy array indexing**

Array indexing is the same as accessing an array element.

The index start with 0 to N.

**Access 1-D arrays**

In [43]:
# get the first element of an array
import numpy as np
arr = np.array([12, 14, 16, 18, 20, 22, 24])
print(f"The first element is: {arr[0]}")

The first element is: 12


In [44]:
# get the second element of an array
import numpy as np
arr = np.array([12, 14, 16, 18, 20, 22, 24])
print(f"The second element is: {arr[1]}")

The second element is: 14


In [45]:
# get the last element of an array
import numpy as np
arr = np.array([12, 14, 16, 18, 20, 22, 24])
print(f"The last element is: {arr[6]}")

The last element is: 24


In [50]:
# arithmetic operations between fourth and sixth elements
import numpy as np
arr = np.array([12, 14, 16, 18, 20, 22, 24])
print(f"The summation of {arr[3]} and {arr[5]} is: {arr[3] + arr[5]}")
print(f"The subtraction of {arr[3]} and {arr[5]} is: {arr[3] - arr[5]}")
print(f"The multiplicaiton of {arr[3]} and {arr[5]} is: {arr[3] * arr[5]}")
print(f"The division of {arr[3]} and {arr[5]} is: {arr[3] / arr[5]}")
print(f"The modulus of {arr[3]} and {arr[5]} is: {arr[3] % arr[5]}")

The summation of 18 and 22 is: 40
The subtraction of 18 and 22 is: -4
The multiplicaiton of 18 and 22 is: 396
The division of 18 and 22 is: 0.8181818181818182
The modulus of 18 and 22 is: 18


**Access 2-D arrays**

In [54]:
# create a 2-D arrays, it is used to represent matrix or 2nd order tensors.
import numpy as np
matrix_number=[[1, 2, 3], [4, 5, 6]]
arr=np.array(matrix_number)
print(f"The 2nd element on 1st row: {arr[0, 1]}")
print(f"The 2nd element on 2nd row: {arr[1, 1]}")
print(f"The 3rd element on 1st row: {arr[0, 2]}")

The 2nd element on 1st row: 2
The 2nd element on 2nd row: 5
The 3rd element on 1st row: 3


**Access 3-D arrays**

In [60]:
# another 3-D arrays with two 2-D arrays
import numpy as np
matrix_number=[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [6, 3, 1]]]
arr=np.array(matrix_number)
print(f"The 3rd element of the 2nd array of the 1st array: {arr[0, 1, 2]}")
print(f"The 2nd element of the 2nd array of the 2nd array: {arr[1, 1, 1]}")
print(f"The 1st element of the 1st array of the 2nd array: {arr[1, 0, 0]}")

The 3rd element of the 2nd array of the 1st array: 6
The 2nd element of the 2nd array of the 2nd array: 3
The 1st element of the 1st array of the 2nd array: 7


**Negative indexing**

In [69]:
# create a 2-D arrays, it is used to represent matrix or 2nd order tensors.
import numpy as np
matrix_number=[[1, 2, 3], [4, 5, 6]]
arr=np.array(matrix_number)
print(f"The last element from 2nd dim: {arr[1, -1]}")
print(f"The 2nd element on 2nd row: {arr[1, -2]}")
print(f"The 2nd element on 2nd row: {arr[-1, -2]}")
print(f"The 1st element on 1st row: {arr[0, -3]}")
print(f"The 1st element on 2nd row: {arr[-1, -3]}")

The last element from 2nd dim: 6
The 2nd element on 2nd row: 5
The 2nd element on 2nd row: 5
The 1st element on 1st row: 1
The 1st element on 2nd row: 4


**NumPy Array Slicing**

---

